using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace JadeDbClient.SourceGenerator
{
    [Generator]
    public class JadeDbMapperGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Find classes with [JadeDbObject]
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            // 2. Generate the source
            context.RegisterSourceOutput(classDeclarations.Collect(), Execute);
        }

        static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            foreach (var attributeList in classDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (context.SemanticModel.GetSymbolInfo(attribute).Symbol is not IMethodSymbol attributeSymbol) continue;
                    
                    string fullName = attributeSymbol.ContainingType.ToDisplayString();
                    if (fullName == "JadeDbClient.Attributes.JadeDbObjectAttribute")
                        return classDeclaration;
                }
            }
            return null;
        }

        static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<ClassDeclarationSyntax?> classes)
        {
            if (classes.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Data;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using JadeDbClient.Initialize;");
            sb.AppendLine();
            sb.AppendLine("namespace JadeDbClient.Generated;");
            sb.AppendLine();
            sb.AppendLine("public static class JadeDbMapperInitializer");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    public static void Initialize()");
            sb.AppendLine("    {");

            foreach (var classDecl in classes.Where(c => c != null))
            {
                var modelName = classDecl!.Identifier.Text;
                sb.AppendLine($"        JadeDbMapperOptions.GlobalMappers[typeof({modelName})] = (reader) => new {modelName}");
                sb.AppendLine("        {");
                
                foreach (var prop in classDecl.Members.OfType<PropertyDeclarationSyntax>())
                {
                    var pName = prop.Identifier.Text;
                    var pType = prop.Type.ToString();
                    
                    // Map types including Nullable versions
                    string mapping = pType switch {
                        "string" => $"reader.IsDBNull(reader.GetOrdinal(\"{pName}\")) ? default : reader.GetString(reader.GetOrdinal(\"{pName}\"))",
                        "int" => $"reader.GetInt32(reader.GetOrdinal(\"{pName}\"))",
                        "int?" => $"reader.IsDBNull(reader.GetOrdinal(\"{pName}\")) ? (int?)null : reader.GetInt32(reader.GetOrdinal(\"{pName}\"))",
                        "long" => $"reader.GetInt64(reader.GetOrdinal(\"{pName}\"))",
                        "long?" => $"reader.IsDBNull(reader.GetOrdinal(\"{pName}\")) ? (long?)null : reader.GetInt64(reader.GetOrdinal(\"{pName}\"))",
                        "DateTime" => $"reader.GetDateTime(reader.GetOrdinal(\"{pName}\"))",
                        "DateTime?" => $"reader.IsDBNull(reader.GetOrdinal(\"{pName}\")) ? (DateTime?)null : reader.GetDateTime(reader.GetOrdinal(\"{pName}\"))",
                        "bool" => $"reader.GetBoolean(reader.GetOrdinal(\"{pName}\"))",
                        "bool?" => $"reader.IsDBNull(reader.GetOrdinal(\"{pName}\")) ? (bool?)null : reader.GetBoolean(reader.GetOrdinal(\"{pName}\"))",
                        "decimal" => $"reader.GetDecimal(reader.GetOrdinal(\"{pName}\"))",
                        "decimal?" => $"reader.IsDBNull(reader.GetOrdinal(\"{pName}\")) ? (decimal?)null : reader.GetDecimal(reader.GetOrdinal(\"{pName}\"))",
                        _ => $"({pType})reader.GetValue(reader.GetOrdinal(\"{pName}\"))" 
                    };

                    sb.AppendLine($"            {pName} = {mapping},");
                }
                sb.AppendLine("        };");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("JadeDbMapperInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
